#!/usr/bin/env python
"""
AI DevOps - Configuration Setup Script
Interactively creates .env file with your tokens
"""

import os
import sys

def print_header():
    print("\n" + "="*60)
    print("  AI DevOps - Configuration Setup")
    print("="*60 + "\n")

def get_user_input(prompt, default="", is_secret=False):
    """Get user input with optional default"""
    if default:
        display_prompt = f"{prompt} [{default}]: "
    else:
        display_prompt = f"{prompt}: "
    
    value = input(display_prompt).strip()
    return value if value else default

def print_section(title):
    """Print a section header"""
    print(f"\n{'─'*60}")
    print(f"  {title}")
    print(f"{'─'*60}\n")

def main():
    print_header()
    
    print("This script will help you configure AI DevOps with your API tokens.")
    print("You can skip any step by pressing Enter.\n")
    
    # Check if .env exists
    if os.path.exists('.env'):
        response = input("⚠️  .env file already exists. Overwrite? (y/n): ").lower()
        if response != 'y':
            print("✅ Keeping existing .env file")
            return
    
    # Collect information
    print_section("1️⃣  GITHUB CONFIGURATION (Required for deployment)")
    
    print("Get your GitHub token from: https://github.com/settings/tokens\n")
    print("Steps:")
    print("  1. Go to https://github.com/settings/tokens")
    print("  2. Click 'Generate new token'")
    print("  3. Name it 'AI DevOps'")
    print("  4. Select scopes: 'repo' and 'admin:repo_hook'")
    print("  5. Click 'Generate token'")
    print("  6. Copy the token (shown only once!)\n")
    
    github_token = get_user_input("Enter your GitHub token (ghp_...)", is_secret=True)
    
    if github_token:
        print("✅ GitHub token will be configured")
    else:
        print("⚠️  Skipping GitHub token (you can add later)")
    
    print_section("2️⃣  RENDER CONFIGURATION (Optional)")
    
    print("Get your Render API key from: https://dashboard.render.com\n")
    print("(Optional - demo mode works without this)\n")
    
    render_key = get_user_input("Enter your Render API key (rnd_...)", is_secret=True)
    
    if render_key:
        print("✅ Render API key will be configured")
    else:
        print("ℹ️  Render key is optional - demo mode will work")
    
    print_section("3️⃣  ENVIRONMENT SETTINGS")
    
    flask_env = get_user_input("Flask environment", "development", is_secret=False)
    flask_debug = get_user_input("Enable debug mode? (true/false)", "false", is_secret=False)
    max_file_size = get_user_input("Max upload size in bytes", "52428800", is_secret=False)
    
    print_section("4️⃣  LOGGING")
    
    log_level = get_user_input("Log level (DEBUG/INFO/WARNING/ERROR)", "INFO", is_secret=False)
    
    # Create .env content
    env_content = f"""# AI DevOps Configuration
# Auto-generated by configuration setup script
# Do NOT commit this file to Git

# Flask Settings
FLASK_ENV={flask_env}
FLASK_DEBUG={flask_debug}

# GitHub Configuration (Required)
GITHUB_TOKEN={github_token if github_token else 'ghp_your_token_here'}
GITHUB_API_URL=https://api.github.com

# Render Configuration (Optional)
RENDER_API_KEY={render_key if render_key else 'rnd_your_key_here'}
RENDER_API_URL=https://api.render.com

# Upload Settings
UPLOAD_FOLDER=uploads
MAX_FILE_SIZE={max_file_size}

# Security
SECRET_KEY=ai-devops-{os.urandom(16).hex()}

# Logging
LOG_LEVEL={log_level}
"""
    
    # Write .env file
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("\n" + "="*60)
        print("✅ Configuration Saved Successfully!")
        print("="*60 + "\n")
    except Exception as e:
        print(f"\n❌ Error saving .env file: {e}\n")
        return
    
    # Summary
    print("📋 Configuration Summary:")
    print(f"  • Environment: {flask_env}")
    print(f"  • Debug mode: {flask_debug}")
    print(f"  • GitHub token: {'✅ Configured' if github_token else '⚠️  Not configured'}")
    print(f"  • Render API key: {'✅ Configured' if render_key else '⚠️  Not configured'}")
    print(f"  • Max upload: {max_file_size} bytes")
    print(f"  • Log level: {log_level}")
    
    print("\n🎉 Setup Complete!\n")
    
    print("Next steps:")
    print("  1. Restart Flask app: python app.py")
    print("  2. Open: http://localhost:5000")
    print("  3. Deploy your first project!\n")
    
    print("❓ Need help?")
    print("  • Read CONFIG_SETUP.md for detailed info")
    print("  • Check README.md for troubleshooting")
    print("  • View .env file to edit settings\n")

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user\n")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Error: {e}\n")
        sys.exit(1)
